apiVersion: v1
kind: Service
metadata:
  name: wallet-api-service
  namespace: wallet
  labels:
    app: wallet-api
spec:
  type: ClusterIP
  selector:
    app: wallet-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: wallet-api-lb
  namespace: wallet
  labels:
    app: wallet-api
spec:
  type: LoadBalancer
  selector:
    app: wallet-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
